"""MCP tool registry.

Importing this package side-effect-registers every ``@mcp.tool`` against
the shared ``mcp`` instance in :mod:`allegro_mcp.tools._runtime`.
"""

from __future__ import annotations

# Generated by ``make gen-tools`` from the OpenAPI spec.
from . import additional_services as _additional_services  # noqa: F401
from . import additional_services_translations as _additional_services_translations  # noqa: F401
from . import advance_ship_notices as _advance_ship_notices  # noqa: F401
from . import after_sale_services as _after_sale_services  # noqa: F401
from . import allediscount as _allediscount  # noqa: F401
from . import allegro_prices as _allegro_prices  # noqa: F401
from . import auctions_and_bidding as _auctions_and_bidding  # noqa: F401

# Hand-written.
from . import auth as _auth  # noqa: F401
from . import automatic_pricing as _automatic_pricing  # noqa: F401
from . import badge_campaigns as _badge_campaigns  # noqa: F401
from . import batch_offer_modification as _batch_offer_modification  # noqa: F401
from . import billing as _billing  # noqa: F401
from . import categories_and_parameters as _categories_and_parameters  # noqa: F401
from . import charity as _charity  # noqa: F401
from . import classifieds as _classifieds  # noqa: F401
from . import commission_refunds as _commission_refunds  # noqa: F401
from . import compatibility_list as _compatibility_list  # noqa: F401
from . import contacts as _contacts  # noqa: F401
from . import conversions as _conversions  # noqa: F401
from . import customer_returns as _customer_returns  # noqa: F401
from . import delivery as _delivery  # noqa: F401
from . import deposits as _deposits  # noqa: F401
from . import fulfillment_parcels as _fulfillment_parcels  # noqa: F401
from . import fulfillment_products as _fulfillment_products  # noqa: F401
from . import fulfillment_removal as _fulfillment_removal  # noqa: F401
from . import fulfillment_returns as _fulfillment_returns  # noqa: F401
from . import fulfillment_stock as _fulfillment_stock  # noqa: F401
from . import images_and_attachments as _images_and_attachments  # noqa: F401
from . import information_about_marketplaces as _information_about_marketplaces  # noqa: F401
from . import information_about_user as _information_about_user  # noqa: F401
from . import message_center as _message_center  # noqa: F401
from . import offer_bundles as _offer_bundles  # noqa: F401
from . import offer_management as _offer_management  # noqa: F401
from . import offer_rating as _offer_rating  # noqa: F401
from . import offer_tags as _offer_tags  # noqa: F401
from . import offer_translations as _offer_translations  # noqa: F401
from . import order_management as _order_management  # noqa: F401
from . import payments as _payments  # noqa: F401
from . import points_of_service as _points_of_service  # noqa: F401
from . import post_purchase_issues as _post_purchase_issues  # noqa: F401
from . import pricing as _pricing  # noqa: F401
from . import products as _products  # noqa: F401
from . import public_user_information as _public_user_information  # noqa: F401
from . import rebates_and_promotions as _rebates_and_promotions  # noqa: F401
from . import responsible_persons as _responsible_persons  # noqa: F401
from . import responsible_producers as _responsible_producers  # noqa: F401
from . import shipment_management as _shipment_management  # noqa: F401
from . import size_tables as _size_tables  # noqa: F401
from . import tax_identification_number as _tax_identification_number  # noqa: F401
from . import tax_settings as _tax_settings  # noqa: F401
from . import user_s_offer_information as _user_s_offer_information  # noqa: F401
